{% set name = "ndonnx" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ndonnx-{{ version }}.tar.gz
  sha256: fe4194118ef8ae5297724fb716f73b1af440537f7cb311837c399de29cda382d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.10
    - numpy
    - spox >=0.10
    - typing_extensions
    - onnx

test:
  imports:
    - ndonnx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantco/ndonnx
  summary: ONNX backed array library compliant with Array API standard.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adityagoel4512
    - cbourjau
