{% set name = "ndonnx" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ndonnx-{{ version }}.tar.gz
  sha256: d2d2da3d250ed78fa8cbe7fa2a7478b8a7d10828e7551a4f3c7b24eb4b56fef9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.10
    - numpy
    - spox >=0.10
    - typing-extensions
    - onnx

test:
  imports:
    - ndonnx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantco/ndonnx
  summary: ONNX backed array library compliant with Array API standard.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adityagoel4512
    - cbourjau
